const typeEnum = [
  "feat",
  "fix",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
  "chore",
  "revert",
  "merge",
];

module.exports = {
  rules: {
    "type-enum": [2, "always", typeEnum],
    "subject-empty": [2, "never"],
    "subject-max-length": [2, "always", 114],
    "subject-full-stop": [2, "never", "."],
  },
  prompt: {
    messages: {
      type: "请选择提交类型:",
      scope: "请输入影响范围（可选）:",
      customScope: "请输入自定义影响范围:",
      subject: "请输入简短描述（必填）:",
      body: "请输入详细描述（可选，使用 | 换行）:",
      breaking: "请输入破坏性变更说明（可选，使用 | 换行）:",
      footer: "请输入关联的 Issues（可选，使用 | 换行）:",
      footerPrefixesSelect: "请选择关联 Issue 类型（可选）:",
      customFooterPrefix: "请输入自定义 Issue 前缀:",
      confirmCommit: "确认提交以上内容？",
    },
    types: [
      { value: "feat", name: "feat:     新增功能" },
      { value: "fix", name: "fix:      修复缺陷" },
      { value: "docs", name: "docs:     仅文档变更" },
      { value: "style", name: "style:    代码风格/格式调整" },
      { value: "refactor", name: "refactor: 重构（不修复缺陷也不新增功能）" },
      { value: "perf", name: "perf:     性能优化" },
      { value: "test", name: "test:     测试相关" },
      { value: "build", name: "build:    构建系统或依赖变更" },
      { value: "ci", name: "ci:       CI 配置或脚本变更" },
      { value: "chore", name: "chore:    日常维护或杂项" },
      { value: "revert", name: "revert:   回滚提交" },
      { value: "merge", name: "merge:    合并分支" },
    ],
    scopes: ["app", "ui", "config", "tooling", "docs", "tests", "ci"],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlias: "手动输入",
    emptyScopesAlias: "无影响范围",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    customIssuePrefixAlias: "手动输入",
    emptyIssuePrefixAlias: "跳过",
    subjectLimit: 114,
  },
};
